#combining all pterplot data

find *.tab -type f -print -exec awk  'BEGIN{OFS="\t"}NR>1  {print $0, (FNR>1 ? FILENAME : "name")}' {} \; | awk 'NF>=3' > all_peterplot_data.tab

#clsuter if sum
awk 'NR==FNR{a[$1]=$0; next} $1 in a{print a[$1], $2, $3}'  all_with_name_SPRET_only_names.tab all_trinity_piRNA_proporation_feature_only.count.tab | awk '{key = $2 FS $4; sum[key] += $3} END {for (k in sum) {split(k, arr, FS); print arr[1], sum[k], arr[2]}}' > all_count_sum_cluster_id_SPRET.tab &

#panGenome
./minigraph -cxggs -t48 ../fasta/C57BL_6NJ.fa ../fasta/AKR_J.fa  ../fasta/BALB_cJ.fa ../fasta/A_J.fa  ../fasta/CBA_J.fa ../fasta/C3H_HeJ.fa ../fasta/NOD_ShiLtJ.fa ../fasta/FVB_NJ.fa ../fasta/DBA_2J.fa  ../fasta/129S1_SvImJ.fa  ../fasta/NZO_HlLtJ.fa ../fasta/LP_J.fa ../fasta/WSB_EiJ.fa ../fasta/PWK_PhJ.fa  ../fasta/CAST_EiJ.fa ../fasta/SPRET_EiJ.fa  > ../all_strains.gfa
minigraph -xggs -t 12 -L 50 -l 50000   ../ref_genome/GRCm39.106.fasta ../
../resources/REL-2205-Assembly/CAST_EiJ_chromosomes_MT.fasta ../../resources/REL-2205-Assembly/C57BL_6NJ_chromosomes_MT.fasta ../../resources/REL-2205-A
ssembly/LP_J_chromosomes_MT.fasta ../../resources/REL-2205-Assembly/C3H_HeJ_chromosomes_MT.fasta ../../resources/REL-2205-Assembly/WSB_EiJ_chromosomes_M
T.fasta ../../resources/REL-2205-Assembly/DBA_2J_chromosomes_MT.fasta ../../resources/REL-2205-Assembly/CBA_J_chromosomes_MT.fasta ../../resources/REL-2
205-Assembly/FVB_NJ_chromosomes_MT.fasta ../../resources/REL-2205-Assembly/BALB_cJ_chromosomes_MT.fasta ../../resources/REL-2205-Assembly/129S1_SvImJ_ch
romosomes_MT.fasta ../../resources/REL-2205-Assembly/A_J_chromosomes_MT.fasta ../../resources/REL-2205-Assembly/SPRET_EiJ_chromosomes_MT.fasta  ../../re
sources/REL-2205-Assembly/NZO_HlLtJ_chromosomes_MT.fasta ../../resources/REL-2205-Assembly/NOD_ShiLtJ_chromosomes_MT.fasta  ../../resources/REL-2205-Ass
embly/AKR_J_chromosomes_MT.fasta ../../resources/REL-2205-Assembly/PWK_PhJ_chromosomes_MT.fasta > allGenomes.gfa

bedtools intersect -a {sid}-12.5dpp.bed12.bed.gz -b {sid}-12.5dpp.bed12.bed.gz {sid}-16.5dpc.bed12.bed.gz {sid}-20.5dpp.bed12.bed -sorted -wo -s -names {sid}-12.5dpp {sid}-16.5dpc {sid}-20.5dpp


####te count 
cat all_TE_count_pacBio.tab| grep -v Geneid| awk '{split($0,a,"\t");split(a[8],b,"/");split(b[2],c,".featureCounts"); print a[1]"\t" a[7] "\t" c[1]}' > all_TE_only_count_pacBio.tab 

####trinity lifoff 

liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-16.5dpc.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-16.5dpc.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-AKR_J-16.5dpc.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/AKR_J-16.5dpc.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-20.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-20.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-WSB_EiJ-20.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/WSB_EiJ-20.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/SPRET_EiJ/SPRET_EiJ.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/SPRET_EiJ/SPRET_EiJ.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/resources/REL-2205-Assembly/SPRET_EiJ_chromosomes_MT.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/liftoff/SPRET_EiJ.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-16.5dpc.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-16.5dpc.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-AKR_J-16.5dpc.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/AKR_J-16.5dpc.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-12.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-12.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-WSB_EiJ-12.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/WSB_EiJ-12.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/129S1_SvImJ/trinity-129S1_SvImJ-12.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/129S1_SvImJ/trinity-129S1_SvImJ-12.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-129S1_SvImJ-12.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/129S1_SvImJ-12.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/SPRET_EiJ/trinity-SPRET_EiJ-20.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/SPRET_EiJ/trinity-SPRET_EiJ-20.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-SPRET_EiJ-20.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/SPRET_EiJ-20.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-12.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-12.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-WSB_EiJ-12.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/WSB_EiJ-12.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/SPRET_EiJ/SPRET_EiJ.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/SPRET_EiJ/SPRET_EiJ.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/resources/REL-2205-Assembly/SPRET_EiJ_chromosomes_MT.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/liftoff/SPRET_EiJ.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/129S1_SvImJ/trinity-129S1_SvImJ-12.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/129S1_SvImJ/trinity-129S1_SvImJ-12.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-129S1_SvImJ-12.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/129S1_SvImJ-12.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-12.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-12.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-WSB_EiJ-12.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/WSB_EiJ-12.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-16.5dpc.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-16.5dpc.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-AKR_J-16.5dpc.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/AKR_J-16.5dpc.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/129S1_SvImJ/trinity-129S1_SvImJ-12.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/129S1_SvImJ/trinity-129S1_SvImJ-12.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-129S1_SvImJ-12.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/129S1_SvImJ-12.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/129S1_SvImJ/trinity-129S1_SvImJ-12.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/129S1_SvImJ/trinity-129S1_SvImJ-12.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-129S1_SvImJ-12.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/129S1_SvImJ-12.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-16.5dpc.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-16.5dpc.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-AKR_J-16.5dpc.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/AKR_J-16.5dpc.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-12.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-12.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-WSB_EiJ-12.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/WSB_EiJ-12.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/SPRET_EiJ/trinity-SPRET_EiJ-16.5dpc.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/SPRET_EiJ/trinity-SPRET_EiJ-16.5dpc.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-SPRET_EiJ-16.5dpc.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/SPRET_EiJ-16.5dpc.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/129S1_SvImJ/trinity-129S1_SvImJ-16.5dpc.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/129S1_SvImJ/trinity-129S1_SvImJ-16.5dpc.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-129S1_SvImJ-16.5dpc.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/129S1_SvImJ-16.5dpc.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-12.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-12.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-AKR_J-12.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/AKR_J-12.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/WSB_EiJ/WSB_EiJ.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/WSB_EiJ/WSB_EiJ.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/resources/REL-2205-Assembly/WSB_EiJ_chromosomes_MT.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/liftoff/WSB_EiJ.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/SPRET_EiJ/trinity-SPRET_EiJ-20.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/SPRET_EiJ/trinity-SPRET_EiJ-20.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-SPRET_EiJ-20.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/SPRET_EiJ-20.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-16.5dpc.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-16.5dpc.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-WSB_EiJ-16.5dpc.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/WSB_EiJ-16.5dpc.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-20.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/AKR_J/trinity-AKR_J-20.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-AKR_J-20.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/AKR_J-20.5dpp.log &
liftoff -mm2_options ='-x asm20'  -exclude_partial -g /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.gtf -o /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-20.5dpp.Trinity.500.gff3 -u /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/trinity_genome/WSB_EiJ/trinity-WSB_EiJ-20.5dpp.Trinity.500.unmapped.txt /lustre/scratch123/hgi/projects/mouse_epi/users/tdd/projects/mice16/results/trinity/trinity-WSB_EiJ-20.5dpp.Trinity.500.fasta /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/results/ref_genome/GRCm39.106.fasta > /lustre/scratch123/hgi/projects/mouse_epi/users/naru/inProgres/mice_PiRNA/log/trinity_genome/WSB_EiJ-20.5dpp.log &



#pangenome 
 minigraph -xggs -c -t 50 -L 50 -l 50000 data/C57BL_6NJ.fasta data/BALB_cJ.fasta data/A_J.fasta data/FVB_NJ.fasta data/C3H_HeJ.fasta data/LP_J.fasta data/129S1_SvImJ.fasta data/DBA_2J.fasta data/AKR_J.fasta data/CBA_J.fasta data/NZO_HlLtJ.fasta data/NOD_ShiLtJ.fasta data/WSB_EiJ.fasta data/CAST_EiJ.fasta data/PWK_PhJ.fasta data/SPRET_EiJ.fasta > allGenomes.gfa &